import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "dist",
    "playwright-report",
    "test-results",
  ],
  rules: {
    curly: "off",
    "func-style": "off",
    "import/consistent-type-specifier-style": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-empty-function": "off",
    "no-inline-comments": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-shadow": "off",
    "no-use-before-define": "off",
    "no-plusplus": "off",
    "operator-assignment": "off",
    "prefer-arrow-callback": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "node/callback-return": "off",
    "promise/prefer-await-to-callbacks": "off",
    "typescript/consistent-return": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-import-type-side-effects": "off",
    "typescript/no-misused-spread": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/prefer-readonly": "off",
    "typescript/promise-function-async": "off",
    "typescript/return-await": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/new-for-builtins": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-typeof-undefined": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-at": "off",
    "unicorn/prefer-math-trunc": "off",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-replace-all": "off",
  },
});
